---
title: "R Experiments on Dissertation ABM"
output: html_notebook
editor_options: 
  chunk_output_type: console
---

```{r setup}
library(dplyr)
library(purrr)
library(ggplot2)
library(nlexperiment)

knitr::opts_knit$set(root.dir = "C:/Z-Work/Dissertation/Data and analysis/Dissertation ABM paper/Model experiment data")
```
 

## Windows
```{r}
nl_netlogo_path("C:/Program Files/NetLogo 6.0.2/app")
setwd("C:/Z-Work/Dissertation/Data and analysis/Dissertation ABM paper")
module_file_pathWindows <- "C:/Z-Work/Dissertation/Data and analysis/Dissertation ABM paper/Dissertation_ABM_0526_QuickerVersion.nlogo"
```

## experiment using windows

```{r}
nl_netlogo_path("C:/Program Files/NetLogo 6.0.2/app")
setwd("C:/Z-Work/Dissertation/Data and analysis/Dissertation ABM paper")
module_file_pathWindows <- "C:/Z-Work/Dissertation/Data and analysis/Dissertation ABM paper/Dissertation_ABM_0526_QuickerVersion.nlogo"


experiment <- nl_experiment(
  model_file = module_file_pathWindows,
  repetitions = 10,
  random_seed = 1:10,
  iterations = 720,
  
  param_values = nl_param_oat(
    n=10,
    meanRIskThreshold = c(0.2,0.4,0.5),
    scanningRange = c(1,3,6),
    numWindows = c(0,4,10),
    badImpact = 0.08,
    impactReductionRate = c(0.1,0.15,0.3),
    maxCopingReduction = c(0,0.20,0.45),
    adaptationCost = 6.5,
    capBoost = c(0, 3,5),
    simTicks = 720
  ),
  run_measures = measures(
    copingNum = "count orgs with [coping-change?]",
    adaptNum = "count orgs with [adaptation-change?]"
    # disasterWindows="[disasterWindows] of orgs",
    # orgWindows="[orgWindows] of orgs"
  ),
  agents_step = list(
    orgs = agent_set(
      vars = c("adaptation-change?", "coping-change?", "riskPerceptionThreshold", "expectedImpact", "solEfficacy","window-open?","window-missed?","insufBoost?","originalCapacity"),
      agents = "orgs")
  ),
  mapping = nl_default_mapping
)
# cbind(experiment$mapping)  #check parameter names mapping

result1 <- nl_run(experiment,parallel = T)
cbind(experiment$mapping)  #check parameter names mapping
nl_show_params(experiment)


```




## Analyze data
```{r}
data1Run <- nl_get_run_result(result1)

ggplot(data1Run, aes(x = factor(capBoost), y = adaptNum)) +
  geom_boxplot(fill = "grey") +
  labs(y = "number of adapting orgs", x = "capacity boost") +
  theme_minimal()


ggplot(data1Run, aes(x = factor(capBoost), y = copingNum)) +
  geom_boxplot(fill = "grey") +
  labs(y = "number of adapting orgs", x = "capacity boost") +
  theme_minimal()
```

## Check adaptation conditions
```{r}
data1Step <- nl_get_result(result1, type = "agents_step", sub_type = "orgs")


run1<-data1Step %>% filter(run_id==1)
run1<-run1 %>% mutate(satisfied=ifelse(expectedImpact > riskPerceptionThreshold, 0,1))


View(run1 %>% filter(satisfied==FALSE & `adaptation-change?`==TRUE) %>% select(`window-open?`,`window-missed?`,satisfied,`adaptation-change?`))

#check whether windows are missed because of under risk perception threshold
View(run1 %>% filter(`window-open?`==T & `window-missed?`==T) %>% select(`window-open?`,`window-missed?`,satisfied))

#check things when windows are open
View(run1 %>% filter(`window-open?`==T ) %>% select(`window-open?`,`window-missed?`,satisfied, `insufBoost?`,`adaptation-change?`))
#three conditions: 1) beyond threshold, 2) windows-open; 3) sufficient boost


```
 
 ## graph adaptation over time
```{r}

data1StepAgg<-data1Step %>% group_by(step_id,param_set_id) %>% summarise(adaptNum=sum(`adaptation-change?`),copingNum=sum(`coping-change?`), missedNum=sum(`window-missed?`), openNum=sum(`window-open?`),`insufBoost?`=sum(`insufBoost?`))


AverageAdapt<- data1StepAgg %>% group_by(step_id) %>% summarise(adaptNum=mean(adaptNum), copingNum=mean(copingNum))


ggplot(AverageAdapt %>% filter(step_id!=c(1,2,3,4)))+
  geom_line(aes(x=step_id, y=adaptNum),color="red")+
  geom_line(aes(x=step_id, y=copingNum),color="green")+
  theme_minimal()

```


## sensitivity analysis
```{r}
dataRun<-nl_get_run_result(result1)

ggplot(dataRun, aes(x=factor(numWindows),y=adaptNum))+
  geom_boxplot()
ggplot(dataRun, aes(x=factor(impactReductionRate),y=adaptNum))+
  geom_boxplot()
ggplot(dataRun, aes(x=factor(maxCopingReduction),y=adaptNum))+
  geom_boxplot()
ggplot(dataRun, aes(x=factor(capBoost),y=adaptNum))+
  geom_boxplot()


data_long<-gather(dataRun,key="parameter",value="value",c("numWindows","impactReductionRate","maxCopingReduction","capBoost"))

ggplot(data_long,aes(x=value,y=adaptNum))+
  geom_point(alpha=0.4)+
  facet_wrap(~parameter,scales="free_x")+
  theme_bw()


```


## AGAVE
Need to change the wd to github data

```{r}
nl_netlogo_path("/packages/7x/netlogo/6.0.2/app") # to netlogo installation
nl_netlogo_path()
# setwd("/home/fzhang59/dev/EW-model")
model_file_path <- "C:/Z-Work/Dissertation/Data and analysis/Dissertation ABM paper/Dissertation ABM 0522.nlogo"
```

